---
title: "Curriculum vitae"
title-block-banner: false
---


## Formation

09/2018 – 11/2021 Thèse à l'Université de Montpellier en biologie de la conservation, sous la direction de Vincent Devictor et Vasilis Dakos. Titre : « Tout est lié » : résponses complexes de la biodiversité aux changements globaux et déterminants socio-économique.

09/2017 – 08/2018 Master (2ème année) Biodiversité, Ecologie et Évolution, Université de Montpellier.

09/2014 – 08/2017 École Normale Supérieur de Lyon.

## Emplois

11/2025 – en cours Postdoctorat en biologie de la conservation et économie écologique, CESAB, FRB, Montpellier, France.

11/2023 – 10/2025 Postdoctorat en biologie de la conservation, UMR TETIS, INRAE, Montpellier, France.

01/2023 – 09/2023 Postdoctorat en économie écologique, Laboratoire Écologie, Systématique et Évolution, Université Paris Saclay, Saclay, France.

01/2022 – 12/2022 Postdoctorat en biologie de la conservation, Landscape Ecology Department, Swedish University of Agricultural Sciences, Uppsala, Suède.

09/2018 – 11/2021 Thèse, Institut des Sciences de l’Évolution de Montpellier, Université de Montpellier, Montpellier, France.

09/2014 – 08/2018  Élève fonctionnaire stagiaire, École Normale Supérieure de Lyon, Lyon, France.

## Encadrement

01/2025 – 06/2025 Co-supervision d'un étudiant en M2 : Pattrons spatiaux et changements temporels dans les stratégies migratoires des oiseaux européens

01/2020 – 06/2020 Co-supervision d'un étudiant en M2 : Une approche non linéaire de la dynamique temporelle à long terme chez les oiseaux européens confrontés à des changements globaux.

01/2019 – 06/2019 Co-supervision d'une étudiante en M2 : Identification des trajectoires non linéaires non linéaires de la biodiversité dans le cadre de régimes de perturbation et exploration des caractéristiques écologiques spécifiques appliquées aux oiseaux communs.

## Enseignement

10/2024 5h de cours d'introduction au lien économie-environnement, AgroParisTech.

09/2019 – 06/2020 64 heures d'enseignement en TD, Université de Montpellier.

09/2018 – 06/2019 48 heures d'enseignement en TD, Université de Montpellier.

